
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: test
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource  # 默 com.zaxxer.hikari.HikariDataSource 数据库连接池类型
  jpa:
    show-sql: true # 控制台打印sql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  batch:
    job:
      enabled: false      # 项目启动完成是否自动执行定义的Job 默 true
#      names: job1,job2   # 启动时要执行的Job，默认执行全部Job
    jdbc:
      initialize-schema: always   # 项目启动时执行建表SQL 默 embedded
      table-prefix: batch_        # 表的前缀  默 batch_
#      schema:                    # 初始化执行的*.sql文件位置 默 classpath:org/springframework/batch/core/schema-@@platform@@.sql
