package com.zja.webservices.service.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-10-29T15:42:49.608+08:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://service.webservices.zja.com/wsdl", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "getName", targetNamespace = "http://service.webservices.zja.com/wsdl", className = "com.zja.webservices.service.wsdl.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://service.webservices.zja.com/wsdl", className = "com.zja.webservices.service.wsdl.GetNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getName(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod(action = "oKongAction")
    @RequestWrapper(localName = "oKongOperationName", targetNamespace = "http://service.webservices.zja.com/wsdl", className = "com.zja.webservices.service.wsdl.OKongOperationName")
    @ResponseWrapper(localName = "oKongOperationNameResponse", targetNamespace = "http://service.webservices.zja.com/wsdl", className = "com.zja.webservices.service.wsdl.OKongOperationNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String oKongOperationName(

        @WebParam(name = "paramName", targetNamespace = "")
        java.lang.String paramName
    );

    @WebMethod
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service.webservices.zja.com/wsdl", className = "com.zja.webservices.service.wsdl.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service.webservices.zja.com/wsdl", className = "com.zja.webservices.service.wsdl.GetUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.zja.webservices.service.wsdl.UserDTO getUser(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );
}
